import Images from '../assets/images/images';

export const Categoty= [
    {
        name:'Dog',
        img: Images.dog(),
        imageD:Images.dogd(),
        typeimg : Images.type(),
        foodimg : Images.fooddog(),
        mammal:Images.mammal(),
        endangered:Images.endangered(),
        detail:'The dog is a domesticated descendant of the wolf. Also called the domestic dog, it is derived from extinct gray wolves and the gray wolf is the dog closest living relativeThe dog was the first species to be domesticated by humans.',
        food:'Meat.',
        mating:'Throughout the year.',
        middleAge:'10-13 year.',
        id: 1,
    },
    {
        name:'Cat',
        img: Images.cat(),
        imageD:Images.catd(),
        typeimg : Images.type(),
        foodimg : Images.fooddog(),
        mammal:Images.mammal(),
        endangered:Images.endangered(),
        detail:'The cat commonly referred to as the domestic cat or house cat, is the only domesticated species in the family Felidae. Recent advances in archaeology and genetics have shown that the domestication of the cat occurred in the Near East around 7500 BC. It is commonly kept as a house pet and farm cat, but also ranges freely as a feral cat avoiding human contact.',
        food:'Meat , Chickens , Fish.',
        mating:'Usually in spring and summer.',
        middleAge:'12-18 year.',
        id: 2,
    },
    {
        name:'Rabbit',
        img: Images.rabbit(),
        imageD:Images.rabbitd(),
        typeimg : Images.type(),
        foodimg : Images.fooddog(),
        mammal:Images.mammal(),
        endangered:Images.endangered(),
        detail:'Rabbits, also known as bunnies or bunny rabbits, are small mammals in the family Leporidae (which also includes the hares), which is in the order Lagomorpha (which also includes the pikas). Oryctolagus cuniculus is the European rabbit, including its descendants, the world 305 breeds of domestic rabbit. Sylvilagus includes 13 wild rabbit species, among them the seven types of cottontail.',
        food:'Carrot , Lettuce.',
        mating:'At 5 months old.',
        middleAge:'3-9 year.',
        id: 3,
    },
    {
        name:'Turtle',
        img: Images.turtle(),
        imageD:Images.turtled(),
        typeimg : Images.type(),
        foodimg : Images.fooddog(),
        mammal:Images.mammal(),
        endangered:Images.endangered(),
        detail:'Turtles are reptiles of the order Testudines, characterized by a special shell developed mainly from their ribs. Modern turtles are divided into two major groups, the Pleurodira (side necked turtles) and Cryptodira (hidden necked turtles), which differ in the way the head retracts. There are 360 living and recently extinct species of turtles, including land-dwelling tortoises and freshwater terrapins.',
        food:'Meat , plants.',
        mating:'Usually in spring and summer.',
        middleAge:'More than 100 years.',
        id: 4,
    },
    {
        name:'Bird',
        img: Images.bird(),
        imageD:Images.birdd(),
        typeimg : Images.type(),
        foodimg : Images.fooddog(),
        mammal:Images.mammal(),
        endangered:Images.endangered(),
        detail:'Birds are a group of warm-blooded vertebrates constituting the class Aves characterised by feathers, toothless beaked jaws, the laying of hard-shelled eggs, a high metabolic rate, a four-chambered heart, and a strong yet lightweight skeleton. Birds live worldwide and range in size from the 5.5 cm (2.2 in) bee hummingbird to the 2.8 m (9 ft 2 in) common ostrich. There are over 11,000 living species, more than half of which are passerine, or "perching" birds.',
        food:'Vegetables.',
        mating:'Usually in spring and summer.',
        middleAge:'5-10 year.',
        id: 5,
    },
    {
        name:'Horse',
        img:Images.horse(),
        imageD:Images.horsed(),
        typeimg : Images.type(),
        foodimg : Images.fooddog(),
        mammal:Images.mammal(),
        endangered:Images.endangered(),
        detail:'The horse is a domesticated, one-toed, hoofed mammal. It belongs to the taxonomic family Equidae and is one of two extant subspecies of Equus ferus. The horse has evolved over the past 45 to 55 million years from a small multi-toed creature, close to Eohippus, into the large, single-toed animal of today. Humans began domesticating horses around 4000 BCE, and their domestication is believed to have been widespread by 3000 BCE. Horses in the subspecies caballus are domesticated, although some domesticated populations live in the wild as feral horses.',
        food:'Barley.',
        mating:'Winter & continues until spring.',
        middleAge:'25-30 year.',
        id: 6,
    },
    {
        name:'Fish',
        img: Images.fish(),
        imageD:Images.fishd(),
        typeimg : Images.type(),
        foodimg : Images.fooddog(),
        mammal:Images.mammal(),
        endangered:Images.endangered(),
        detail:'A fish is an aquatic, gill-bearing vertebrate animal with swimming fins and a hard skull, but lacking limbs with digits. Fish can be grouped into the more basal jawless fish and the more common jawed fish, the latter including all living cartilaginous and bony fishes, as well as the extinct placoderms and acanthodians. Most fish are cold-blooded, their body temperature varying with the surrounding water, though some large active swimmers like white shark and tuna can hold a higher core temperature. Many fish can communicate acoustically with each other, such as during courtship displays.',
        food:'Algae or Vegetables.',
        mating:'Winter & continues until spring.',
        middleAge:'2-5 year.',
        id: 7,
    },
    {
        name:'Snake',
        img:Images.snake(),
        imageD:Images.snaked(),
        typeimg : Images.type(),
        foodimg : Images.fooddog(),
        mammal:Images.mammal(),
        endangered:Images.endangered(),
        detail:'Snakes are elongated, limbless, carnivorous reptiles of the suborder Serpentes Like all other squamates, snakes are ectothermic, amniote vertebrates covered in overlapping scales. Many species of snakes have skulls with several more joints than their lizard ancestors, enabling them to swallow much larger than their heads (cranial kinesis). To accommodate their narrow bodies, snakes paired organs (such as kidneys) appear one in front of the other instead of side by side, and most have only one functional lung.',
        food:'Mice.',
        mating:'Usually in spring and summer.',
        middleAge:'Lives 18 years.',
        id: 8,
    }

]